name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
              env:
                  CI: true
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            - run: echo DATABASE_URL="$DATABASE_URL" >> .env.production
            - run: echo NEXTAUTH_SECRET="$NEXTAUTH_SECRET" >> .env.production
            - run: echo NEXTAUTH_URL="$NEXTAUTH_URL" >> .env.production
            - run: npm install
            - run: npm run build --if-present
            - run: pm2 reload librarysite
