name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            
            - name: Create env file
              uses: SpicyPizza/create-envfile@v1.3
              with:
                envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
                envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                envkey_NEXTAUTH_URL: https://kirihi.me
                file_name: .env.production
                
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
              env:
                  CI: true
#                   DATABASE_URL: ${{ secrets.DATABASE_URL }}
#                   NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
#                   NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            - run: npm install
            - run: npm run build --if-present
            - run: pm2 reload librarysite
